"""
The pre-write asset gate (`arklight.compiler.asset_check`, wired into
`arklight.compiler.pipeline.build`): every asset the site references must
exist, by exact name, in `assets/` -- or be generated by the build --
or the build halts before writing anything.
"""

from pathlib import Path

import pytest

from arklight.compiler.pipeline import CompileError, build

SITE_HEAD = "# include <stdlib.ARKlight>\nsite = Site()\n"


def make_site(tmp_path: Path, page_body: str, *, extra_pages: str = "") -> Path:
    path = tmp_path / "site.py"
    path.write_text(
        SITE_HEAD
        + f'\n@site.page("/")\ndef home():\n    return Page({page_body}, title="Home")\n'
        + extra_pages
    )
    return path


def add_asset(tmp_path: Path, rel: str, data: str = "x") -> None:
    target = tmp_path / "assets" / rel
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(data)


def test_all_present_builds_and_copies(tmp_path):
    add_asset(tmp_path, "img/logo.png")
    site = make_site(tmp_path, 'Image(src="assets/img/logo.png", alt="l")')
    out = tmp_path / "dist"
    build(site, out)
    assert (out / "assets" / "img" / "logo.png").exists()


def test_missing_asset_halts_and_writes_nothing(tmp_path, capsys):
    add_asset(tmp_path, "logo.png")
    site = make_site(tmp_path, 'Image(src="assets/typo.png", alt="t")')
    out = tmp_path / "dist"
    with pytest.raises(CompileError, match="Asset check failed"):
        build(site, out)
    assert not out.exists()  # nothing written, not even the pages
    err = capsys.readouterr().err
    assert "ASSET CHECK FAILED" in err
    assert "assets/typo.png" in err
    assert "logo.png" in err  # directory contents are shown


def test_report_is_written_to_stderr_even_with_a_silent_on_stage(tmp_path, capsys):
    site = make_site(tmp_path, 'Image(src="assets/none.png", alt="n")')
    with pytest.raises(CompileError):
        build(site, tmp_path / "dist", on_stage=lambda _m: None)
    assert "assets/none.png" in capsys.readouterr().err


def test_report_lists_every_problem_not_just_the_first(tmp_path, capsys):
    site = make_site(
        tmp_path,
        'Image(src="assets/a.png", alt="a"), Image(src="assets/b.png", alt="b")',
    )
    with pytest.raises(CompileError, match="2 of 2"):
        build(site, tmp_path / "dist")
    err = capsys.readouterr().err
    assert "assets/a.png" in err and "assets/b.png" in err


def test_wrong_case_is_a_failure_even_where_the_filesystem_would_allow_it(tmp_path, capsys):
    add_asset(tmp_path, "Logo.png")
    site = make_site(tmp_path, 'Image(src="assets/logo.png", alt="l")')
    with pytest.raises(CompileError):
        build(site, tmp_path / "dist")
    err = capsys.readouterr().err
    assert "CASE" in err and "'Logo.png'" in err


def test_wrong_directory_case_is_a_failure(tmp_path, capsys):
    add_asset(tmp_path, "Images/a.png")
    site = make_site(tmp_path, 'Image(src="assets/images/a.png", alt="a")')
    with pytest.raises(CompileError):
        build(site, tmp_path / "dist")
    assert "'Images'" in capsys.readouterr().err


def test_directory_where_a_file_is_expected_fails(tmp_path):
    (tmp_path / "assets" / "logo.png").mkdir(parents=True)
    site = make_site(tmp_path, 'Image(src="assets/logo.png", alt="l")')
    with pytest.raises(CompileError):
        build(site, tmp_path / "dist")


def test_no_assets_folder_at_all_reports_it(tmp_path, capsys):
    site = make_site(tmp_path, 'Image(src="assets/logo.png", alt="l")')
    with pytest.raises(CompileError):
        build(site, tmp_path / "dist")
    assert "does not exist" in capsys.readouterr().err


def test_reference_outside_assets_that_nothing_generates_fails(tmp_path, capsys):
    site = make_site(tmp_path, 'Image(src="sprites/25.png", alt="s")')
    with pytest.raises(CompileError):
        build(site, tmp_path / "dist")
    assert "OUTSIDE-ASSETS" in capsys.readouterr().err


def test_favicon_and_og_image_are_checked(tmp_path, capsys):
    path = tmp_path / "site.py"
    path.write_text(
        SITE_HEAD
        + '\n@site.page("/")\ndef home():\n    return Page(Heading("H"), title="H", '
        'favicon="/assets/fav.ico", og_image="assets/og.png")\n'
    )
    with pytest.raises(CompileError):
        build(path, tmp_path / "dist")
    err = capsys.readouterr().err
    assert "assets/fav.ico" in err and "assets/og.png" in err


def test_url_in_inline_style_is_checked(tmp_path, capsys):
    site = make_site(
        tmp_path,
        'Container(Text("x"), style={"background": "url(assets/bg.png)"})',
    )
    with pytest.raises(CompileError):
        build(site, tmp_path / "dist")
    assert "assets/bg.png" in capsys.readouterr().err


def test_href_into_assets_is_checked_but_other_hrefs_are_not(tmp_path, capsys):
    site = make_site(
        tmp_path,
        'Link("doc", href="assets/guide.pdf"), Link("ext", href="https://example.com"), '
        'Link("mail", href="mailto:a@b.c"), Link("anchor", href="#top"), '
        'Link("unknown", href="/somewhere")',
    )
    with pytest.raises(CompileError, match="1 of 1"):
        build(site, tmp_path / "dist")
    assert "assets/guide.pdf" in capsys.readouterr().err


def test_external_data_route_and_generated_refs_are_not_required(tmp_path):
    site = make_site(
        tmp_path,
        'Image(src="https://cdn.example.com/a.png", alt="e"), '
        'Image(src="data:image/gif;base64,R0lGOD", alt="d"), '
        'Image(src="//cdn.example.com/b.png", alt="p")',
    )
    build(site, tmp_path / "dist")  # nothing local required -> builds fine


def test_query_and_fragment_are_ignored_when_matching(tmp_path):
    add_asset(tmp_path, "logo.png")
    site = make_site(tmp_path, 'Image(src="assets/logo.png?v=3", alt="l")')
    build(site, tmp_path / "dist")


def test_only_referenced_assets_are_required_extras_are_fine(tmp_path):
    add_asset(tmp_path, "used.png")
    add_asset(tmp_path, "unused.png")
    site = make_site(tmp_path, 'Image(src="assets/used.png", alt="u")')
    build(site, tmp_path / "dist")


def test_asset_used_on_a_nested_page_is_reported_with_that_page(tmp_path, capsys):
    site = make_site(
        tmp_path,
        'Heading("h")',
        extra_pages='\n@site.page("/blog/post")\ndef post():\n'
        '    return Page(Image(src="assets/gone.png", alt="g"), title="P")\n',
    )
    with pytest.raises(CompileError):
        build(site, tmp_path / "dist")
    assert "/blog/post" in capsys.readouterr().err
