"""
Template content for `arklight desktop scaffold` -- Linux-only target
for now, per docs/Backends/DESKTOP-BACKEND-IMPLEMENTATION.md and the
architecture in docs/Backends/ARKLIGHT_DESKTOP_BACKEND_PROPOSAL.md.

Every function here is a pure `(...) -> str` (or `-> tuple[str, str]`)
builder -- no disk I/O, same "template builders never touch disk, the
CLI module owns filesystem writes" split `arklight.backend.android.
runtime` already established for the Android backend. Only
`arklight.cli.desktop` (the CLI-facing module) reads a build
directory's bytes and writes anything to disk.

Two things get generated:

- **The native host itself** (`main.c`, `Makefile`, `.gitignore`, a
  freedesktop `.desktop` launcher entry, a GitHub Actions workflow at
  `.github/workflows/desktop-build.yml` (see `_github_ci_workflow_yml`
  -- mirrors the Android backend's own generated workflow, see
  `arklight.backend.android.runtime`'s module docstring), `README.md`)
  -- a small GTK3 + WebKit2GTK program, per the proposal's "native
  host responsibilities" (section 4): create the window, initialize
  the platform WebView, register an in-process `ark:` resource scheme
  backed by an in-memory asset store, load the entry document, and
  enforce a navigation policy that opens anything outside that scheme
  in the user's default external handler instead of navigating the
  app window away from the packaged site.
- **The embedded asset store** (`assets.gen.c`/`assets.gen.h`,
  generated by `generate_assets_source`) -- every file from an
  `arklight build` output directory, embedded as C byte arrays and
  indexed by its build-relative path. This is the "unpacked tree"
  choice the Android backend's Stage 1 also picked as its default
  (see ANDROID-BACKEND-IMPLEMENTATION.md's "Open questions for
  Stage 0"): simpler than parsing a `.ark` bundle's zip/sealing format
  from C, and it keeps the native host free of a zip/crypto
  dependency for this first target. Packing as a real sealed `.ark`
  bundle (matching the proposal's section 5) is future work, tracked
  in DESKTOP-BACKEND-IMPLEMENTATION.md rather than pinned down here.

Byte arrays are plain C literals (`{0x3c, 0x21, ...}`), not a linker
trick (`ld -r -b binary`, `objcopy`, `#embed`) -- portable across
whatever C toolchain the user's distro ships, at the cost of a
noticeably large generated `assets.gen.c` for a large site. Acceptable
for a first Linux-only target; revisit if that ever becomes the
bottleneck a real site hits.
"""

from __future__ import annotations

import re

# GTK/WebKit soname suite this scaffold's Makefile probes for, newest
# first -- see `_makefile`. `webkit2gtk-4.1` is what current
# Debian/Ubuntu/Fedora ship; `webkit2gtk-4.0` is kept as a fallback
# for older distros still on it. Both expose the same API surface
# `main.c` uses here.
_WEBKIT_PKG_CANDIDATES = ("webkit2gtk-4.1", "webkit2gtk-4.0")

# Characters allowed in a generated Makefile/.desktop binary name --
# kept conservative (lowercase letters, digits, hyphens) so the result
# is safe to use unquoted as a Makefile target and a Desktop Entry
# `Exec=` value, regardless of what `app_name` contains.
_BINARY_NAME_DISALLOWED_RE = re.compile(r"[^a-z0-9-]+")


def binary_name(app_name: str) -> str:
    """
    Derive a safe, lowercase, hyphenated binary/target name from
    `app_name` (e.g. `"My Cool Site!"` -> `"my-cool-site"`). Falls
    back to `"arklight-app"` if nothing alphanumeric survives (e.g.
    an app name that's entirely emoji/punctuation) rather than
    producing an empty Makefile target name.
    """
    slug = _BINARY_NAME_DISALLOWED_RE.sub("-", app_name.strip().lower()).strip("-")
    return slug or "arklight-app"


def _c_string_literal(value: str) -> str:
    """Escape `value` for use inside a C string literal (backslashes,
    double quotes, and newlines -- the only characters `main.c`'s
    `#define ARK_*` macros could plausibly receive from an
    `arklight.config.py` author's `app_name`/`window_title`)."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'


def project_files(
    *,
    app_name: str,
    app_id: str,
    window_title: str,
    width: int,
    height: int,
    resizable: bool,
    project_subdir: str | None = None,
) -> dict[str, str]:
    """
    Return `{relative_path: contents}` for every *generated text* file
    in the Linux desktop host project -- everything except the
    embedded asset store (`assets.gen.c`/`assets.gen.h`, built
    separately by `generate_assets_source` since it needs the actual
    build directory's bytes, not just app identity).

    `app_id` is a reverse-DNS identifier (same shape as the Android
    backend's `package_id`) used as the `.desktop` launcher's filename
    and the window's program name (`g_set_prgname`, which GTK uses to
    derive `WM_CLASS`) -- not a Python/Java package, just a stable,
    namespaced identifier for this one app.

    `project_subdir` is forwarded as-is to `_github_ci_workflow_yml`
    -- see that function's own docstring, and `arklight.backend.
    android.runtime.project_files`'s identical parameter, which this
    mirrors.
    """
    name = binary_name(app_name)
    return {
        "main.c": _main_c(app_name, app_id, window_title, width, height, resizable),
        "Makefile": _makefile(name),
        ".gitignore": _GITIGNORE,
        f"{app_id}.desktop": _desktop_entry(app_name, app_id, name),
        ".github/workflows/desktop-build.yml": _github_ci_workflow_yml(
            app_name, name, project_subdir=project_subdir
        ),
        "README.md": _readme_md(app_name, app_id, name),
    }


# ---------------------------------------------------------------------------
# main.c
# ---------------------------------------------------------------------------


def _main_c(
    app_name: str, app_id: str, window_title: str, width: int, height: int, resizable: bool
) -> str:
    return f'''\
/*
 * ARKlight desktop host -- Linux (GTK3 + WebKit2GTK).
 *
 * Generated by `arklight desktop scaffold`; see
 * docs/Backends/DESKTOP-BACKEND-IMPLEMENTATION.md and
 * docs/Backends/ARKLIGHT_DESKTOP_BACKEND_PROPOSAL.md (section 4,
 * "Native host responsibilities") for the design this implements.
 *
 * This is a launcher and resource provider for the packaged ARKlight
 * site in assets.gen.c, not a second application framework: it
 * creates one window, registers an in-process "ark:" resource scheme
 * backed by that embedded asset table, points a WebKitWebView at it,
 * and sends any navigation outside that scheme to the user's default
 * external handler instead of following it in this window. No custom
 * native JavaScript API is exposed to the page (proposal section 10).
 */

#include <gtk/gtk.h>
#include <webkit2/webkit2.h>
#include <string.h>

#include "assets.gen.h"

#define ARK_APP_NAME {_c_string_literal(app_name)}
#define ARK_APP_ID {_c_string_literal(app_id)}
#define ARK_WINDOW_TITLE {_c_string_literal(window_title)}
#define ARK_WINDOW_WIDTH {int(width)}
#define ARK_WINDOW_HEIGHT {int(height)}
#define ARK_RESIZABLE {"TRUE" if resizable else "FALSE"}

/* Look up `path` (as handed to us by WebKitURISchemeRequest, e.g.
 * "/about.html", or "/" for the bare root) in the embedded asset
 * table. Returns NULL if there's no such asset, or if `path` contains
 * a "..segment -- an embedded, read-only asset table never
 * legitimately needs to escape itself, so that's rejected outright
 * rather than resolved (see the proposal's "path traversal is
 * rejected" bundle-test requirement). */
static const ArkAsset *ark_find_asset(const char *path) {{
    if (path == NULL || path[0] == '\\0' || strcmp(path, "/") == 0) {{
        path = "/index.html";
    }}
    if (path[0] == '/') {{
        path++;
    }}
    if (strstr(path, "..") != NULL) {{
        return NULL;
    }}
    for (size_t i = 0; i < ark_asset_count; i++) {{
        if (strcmp(ark_assets[i].path, path) == 0) {{
            return &ark_assets[i];
        }}
    }}
    return NULL;
}}

static void ark_handle_scheme_request(WebKitURISchemeRequest *request, gpointer user_data) {{
    (void) user_data;
    const char *path = webkit_uri_scheme_request_get_path(request);
    const ArkAsset *asset = ark_find_asset(path);

    if (asset == NULL) {{
        GError *error = g_error_new(
            WEBKIT_NETWORK_ERROR, WEBKIT_NETWORK_ERROR_FAILED,
            "ARKlight: resource not found: %s", path ? path : "(null)");
        webkit_uri_scheme_request_finish_error(request, error);
        g_error_free(error);
        return;
    }}

    GInputStream *stream =
        g_memory_input_stream_new_from_data(asset->data, (gssize) asset->len, NULL);
    webkit_uri_scheme_request_finish(request, stream, (gint64) asset->len, asset->mime);
    g_object_unref(stream);
}}

/* Routing/navigation policy (proposal section 9): "ark:" requests are
 * this app's own packaged resources and load normally; everything
 * else (https://, http://, mailto:, ...) is handed to the platform's
 * default external handler instead of navigating this window there --
 * an embedded desktop shell has no business becoming a general-
 * purpose web browser. */
static gboolean ark_decide_policy(WebKitWebView *view, WebKitPolicyDecision *decision,
                                   WebKitPolicyDecisionType type, gpointer user_data) {{
    (void) view;
    (void) user_data;
    if (type != WEBKIT_POLICY_DECISION_TYPE_NAVIGATION_ACTION &&
        type != WEBKIT_POLICY_DECISION_TYPE_NEW_WINDOW_ACTION) {{
        return FALSE;
    }}

    WebKitNavigationPolicyDecision *nav = WEBKIT_NAVIGATION_POLICY_DECISION(decision);
    WebKitNavigationAction *action = webkit_navigation_policy_decision_get_navigation_action(nav);
    WebKitURIRequest *req = webkit_navigation_action_get_request(action);
    const char *uri = webkit_uri_request_get_uri(req);

    if (uri != NULL && g_str_has_prefix(uri, "ark:")) {{
        return FALSE; /* let the WebView load it via our scheme handler */
    }}

    webkit_policy_decision_ignore(decision);
    if (uri != NULL) {{
        GError *error = NULL;
        if (!g_app_info_launch_default_for_uri(uri, NULL, &error)) {{
            g_warning("ARKlight: could not open external link %s: %s", uri,
                      error ? error->message : "unknown error");
            if (error != NULL) {{
                g_error_free(error);
            }}
        }}
    }}
    return TRUE;
}}

int main(int argc, char *argv[]) {{
    /* Sets the program name GTK derives WM_CLASS from -- must happen
     * before gtk_init(). */
    g_set_prgname(ARK_APP_ID);
    gtk_init(&argc, &argv);

    WebKitWebContext *context = webkit_web_context_get_default();
    webkit_web_context_register_uri_scheme(context, "ark", ark_handle_scheme_request, NULL, NULL);

    GtkWidget *window = gtk_window_new(GTK_WINDOW_TOPLEVEL);
    gtk_window_set_title(GTK_WINDOW(window), ARK_WINDOW_TITLE);
    gtk_window_set_default_size(GTK_WINDOW(window), ARK_WINDOW_WIDTH, ARK_WINDOW_HEIGHT);
    gtk_window_set_resizable(GTK_WINDOW(window), ARK_RESIZABLE);
    g_signal_connect(window, "destroy", G_CALLBACK(gtk_main_quit), NULL);

    WebKitWebView *view = WEBKIT_WEB_VIEW(webkit_web_view_new());
    g_signal_connect(view, "decide-policy", G_CALLBACK(ark_decide_policy), NULL);
    gtk_container_add(GTK_CONTAINER(window), GTK_WIDGET(view));

    webkit_web_view_load_uri(view, "ark:///index.html");

    gtk_widget_show_all(window);
    gtk_main();
    return 0;
}}
'''


# ---------------------------------------------------------------------------
# Build files
# ---------------------------------------------------------------------------


def _makefile(binary: str) -> str:
    # Probes for webkit2gtk-4.1 first, falls back to -4.0 -- see
    # `_WEBKIT_PKG_CANDIDATES`. A `for`/`break` loop, not a chained
    # `A && echo X || B && echo Y` one-liner: `&&`/`||` share the same
    # precedence and left-associate, so `(A && echo X) || B` is one
    # group that `&& echo Y` then runs unconditionally against --
    # printing *both* candidates whenever the first one matches. The
    # loop has no such trap. `?=` on PKG_CONFIG (not `=`) lets a
    # caller override it (e.g. `PKG_CONFIG=pkgconf make`) the same way
    # `CC`/`CFLAGS` are already overridable via `make`'s own built-in
    # rules.
    candidates = " ".join(_WEBKIT_PKG_CANDIDATES)
    probe = (
        f"for p in {candidates}; do "
        f"$(PKG_CONFIG) --exists $$p 2>/dev/null && {{ echo $$p; break; }}; "
        f"done"
    )
    return f'''\
# Generated by `arklight desktop scaffold` -- Linux only for now (GTK3
# + WebKit2GTK). See README.md for the system packages this needs.

PKG_CONFIG ?= pkg-config
WEBKIT_PKG := $(shell {probe})

CFLAGS  += -std=c11 -Wall -Wextra $(shell $(PKG_CONFIG) --cflags gtk+-3.0 $(WEBKIT_PKG))
LDLIBS  += $(shell $(PKG_CONFIG) --libs gtk+-3.0 $(WEBKIT_PKG))

SRC := main.c assets.gen.c
OBJ := $(SRC:.c=.o)
BIN := bin/{binary}

.PHONY: all clean run

all: $(BIN)

$(BIN): $(OBJ)
	@mkdir -p bin
	$(CC) $(OBJ) -o $@ $(LDLIBS)

%.o: %.c assets.gen.h
	$(CC) $(CFLAGS) -c $< -o $@

run: $(BIN)
	./$(BIN)

clean:
	rm -f $(OBJ)
	rm -rf bin
'''


_GITIGNORE = """\
# Build output
*.o
/bin/
"""


# ---------------------------------------------------------------------------
# CI
# ---------------------------------------------------------------------------


def _github_ci_workflow_yml(
    app_name: str,
    binary: str,
    *,
    project_subdir: str | None = None,
) -> str:
    """
    A GitHub Actions workflow, entirely on a GitHub-hosted Linux
    runner -- so a scaffolded project gets an automated build the
    moment it's generated, no local C toolchain or GTK3/WebKit2GTK
    dev headers required on the *user's own* machine. Mirrors
    `arklight.backend.android.runtime._github_ci_workflow_yml`'s single
    `assemble-debug` job: install the same apt packages this project's
    own README.md's "Building" section already tells a human to run,
    `make`, then upload `bin/<binary>` as a downloadable artifact.

    No install/launch smoke-test job (the Android workflow's Stage-3
    equivalent) here yet -- that's DESKTOP-BACKEND-IMPLEMENTATION.md's
    own Stage 3, tracked separately rather than folded into this
    function, since it needs a headless `Xvfb` display plus the
    WebKit2GTK runtime libs on the runner (distinct from the `-dev`
    headers this job already installs to *build*), not just this
    job's existing steps. This function only verifies the build
    compiles and links; Stage 3 will add the "does it also launch
    without crashing" check on top of what it produces.

    `project_subdir`, if given, is the project's path relative to the
    repo root the workflow will actually run from -- e.g. `"desktop"`
    when `arklight desktop scaffold` wrote this project into an
    existing repo's `desktop/` subdirectory rather than at that repo's
    own root (see `arklight.cli.desktop._find_enclosing_git_root`,
    itself mirroring `arklight.cli.android._find_enclosing_git_root`).
    When set, the `make` step gets a matching `working-directory:`,
    and the uploaded binary's path is prefixed with it -- otherwise
    `make` looks for a `Makefile` in the checkout root and fails
    immediately, since checkout always happens at the *repo* root, not
    wherever this project was scaffolded into. `None` (the default)
    means this project IS the repo root, matching the original
    no-subdirectory behavior.
    """
    # Used only in the uploaded artifact's display name -- purely
    # cosmetic, so it's slugified defensively rather than validated
    # the way `app_id`/`app_name` are elsewhere in this module. Same
    # reasoning as the Android workflow generator's own `slug`.
    slug = re.sub(r"[^A-Za-z0-9._-]+", "-", app_name).strip("-") or "arklight-app"
    working_directory_line = f"\n        working-directory: {project_subdir}" if project_subdir else ""
    path_prefix = f"{project_subdir}/" if project_subdir else ""
    return f'''\
name: Desktop build

# Builds the native GTK3 + WebKit2GTK host on a GitHub-hosted Linux
# runner on every push/PR, so a build regression is caught without any
# of the dev headers below needing to exist on a contributor's own
# machine. No install/launch smoke test yet -- see
# DESKTOP-BACKEND-IMPLEMENTATION.md's Stage 3.
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Check out the project
        uses: actions/checkout@v4

      - name: Install GTK3 + WebKit2GTK dev headers
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config libgtk-3-dev libwebkit2gtk-4.1-dev

      - name: Build{working_directory_line}
        run: make

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: {slug}-linux
          path: {path_prefix}bin/{binary}
          if-no-files-found: error
'''


def _desktop_entry(app_name: str, app_id: str, binary: str) -> str:
    # Freedesktop Desktop Entry format -- see
    # https://specifications.freedesktop.org/desktop-entry-spec/latest/.
    # `Exec` deliberately has no path prefix: README.md tells the user
    # to either run this from the project's own `bin/` directory or
    # edit `Exec` to an absolute path once they've installed the
    # binary somewhere on PATH -- this scaffold has no reliable way to
    # know that final install location up front. No `Icon=` key for
    # now -- icon support isn't implemented yet, see README.md.
    return f"""\
[Desktop Entry]
Type=Application
Name={app_name}
Exec={binary}
Terminal=false
Categories=Utility;
StartupWMClass={app_id}
"""


def _readme_md(app_name: str, app_id: str, binary: str) -> str:
    return f"""\
# {app_name} (desktop)

Generated by `arklight desktop scaffold` -- a small native GTK3 +
WebKit2GTK host that loads the packaged ARKlight site in
`assets.gen.c` from memory, through an in-process `ark:` resource
scheme. **Linux only for now** -- see
docs/Backends/DESKTOP-BACKEND-IMPLEMENTATION.md in the ARKlight
repository for the staged plan covering other platforms and a real
local `arklight desktop build` command.

## Building

Needs a C compiler, `pkg-config`, and the GTK3 + WebKit2GTK
development headers.

Debian / Ubuntu:

```sh
sudo apt install build-essential pkg-config libgtk-3-dev libwebkit2gtk-4.1-dev
```

Fedora:

```sh
sudo dnf install gcc pkgconf-pkg-config gtk3-devel webkit2gtk4.1-devel
```

Arch Linux:

```sh
sudo pacman -S base-devel pkgconf gtk3 webkit2gtk-4.1
```

Then, from this directory:

```sh
make
./bin/{binary}
```

(or `make run`, which does both).

## What's in here

| File | What it is |
| --- | --- |
| `main.c` | The native host -- window, WebView, `ark:` scheme handler, external-link policy. Hand-editable, but re-running `arklight desktop scaffold` will overwrite it. |
| `assets.gen.c` / `assets.gen.h` | The packaged site (every file from the `arklight build` output directory this was scaffolded from), embedded as C byte arrays. Regenerated fresh on every `arklight desktop scaffold` run -- don't hand-edit. |
| `Makefile` | Builds `bin/{binary}` from the two files above. |
| `{app_id}.desktop` | A [freedesktop Desktop Entry](https://specifications.freedesktop.org/desktop-entry-spec/latest/) launcher. Edit `Exec=` to an absolute path (or put `bin/{binary}` on your `PATH`) and copy it to `~/.local/share/applications/` to add a launcher-menu entry. |
| `.github/workflows/desktop-build.yml` | A GitHub Actions workflow that builds this project on a GitHub-hosted Linux runner on every push/PR and uploads `bin/{binary}` as a downloadable artifact -- no local toolchain needed for that. Regenerated fresh on every `arklight desktop scaffold` run; it's a normal, hand-editable workflow file, not something only this tool may touch. **Note:** this workflow only fires on GitHub if `.github/workflows/` sits at your repository's *root* -- if `arklight desktop scaffold` told you this project is nested inside an existing repo, move this file there first (see that command's own terminal output for the exact paths). |

## Updating the packaged site

Re-run `arklight build`, then `arklight desktop scaffold` again on the
same output directory (into this same project directory) to refresh
`assets.gen.c`/`assets.gen.h` with the new content, then `make` again.

## Not implemented yet

Per docs/Backends/DESKTOP-BACKEND-IMPLEMENTATION.md's staged plan:
app/window icons, a sealed `.ark` bundle as the embedded payload
(this scaffold embeds the unpacked build directory instead -- see
`arklight.backend.desktop.runtime`'s module docstring for why),
a local `arklight desktop build` command that runs this `Makefile` for
you, and Windows/macOS targets. A GitHub Actions CI build is already
included -- see `.github/workflows/desktop-build.yml` above.
"""


# ---------------------------------------------------------------------------
# Embedded asset store (assets.gen.c / assets.gen.h)
# ---------------------------------------------------------------------------

# Bytes per line in a generated byte-array literal -- purely
# cosmetic (keeps `assets.gen.c` from being one line per file), has no
# effect on the compiled output.
_BYTES_PER_LINE = 16


def _c_byte_array_body(data: bytes) -> str:
    lines = []
    for i in range(0, len(data), _BYTES_PER_LINE):
        chunk = data[i : i + _BYTES_PER_LINE]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    return "\n".join(lines)


def generate_assets_source(files: dict[str, bytes]) -> tuple[str, str]:
    """
    Build `(assets.gen.c contents, assets.gen.h contents)` embedding
    every `{build-relative posix path: bytes}` entry in `files` as a C
    byte array, indexed by path in a generated `ark_assets[]` table --
    see the module docstring's "embedded asset store" section for why
    this embeds the unpacked tree rather than a `.ark` bundle.

    `files` is expected already sorted/deterministic-ordered by the
    caller (`arklight.cli.desktop.scaffold_project` walks the build
    directory with `sorted(...)`) -- this function doesn't re-sort, so
    a caller that hands in an unsorted dict gets a non-deterministic
    `assets.gen.c` between runs, which is their bug to avoid, not this
    function's to silently paper over.
    """
    import mimetypes

    header_lines = [
        "/* Generated by `arklight desktop scaffold` -- do not edit by hand,",
        " * re-run the scaffold command instead. See assets.gen.c. */",
        "#pragma once",
        "",
        "#include <stddef.h>",
        "",
        "typedef struct {",
        "    const char *path;   /* build-relative, no leading slash, e.g. \"assets/logo.svg\" */",
        "    const char *mime;",
        "    const unsigned char *data;",
        "    size_t len;",
        "} ArkAsset;",
        "",
        "extern const ArkAsset ark_assets[];",
        "extern const size_t ark_asset_count;",
        "",
    ]
    header = "\n".join(header_lines)

    source_lines = [
        "/* Generated by `arklight desktop scaffold` -- do not edit by hand,",
        " * re-run the scaffold command instead. */",
        '#include "assets.gen.h"',
        "",
    ]

    table_lines = []
    for index, (path, data) in enumerate(files.items()):
        mime, _ = mimetypes.guess_type(path)
        if mime is None:
            mime = "application/octet-stream"
        var = f"ark_asset_{index}"
        source_lines.append(f"static const unsigned char {var}[] = {{")
        if data:
            source_lines.append(_c_byte_array_body(data))
        source_lines.append("};")
        source_lines.append("")
        escaped_path = _c_string_literal(path)
        escaped_mime = _c_string_literal(mime)
        table_lines.append(f"    {{ {escaped_path}, {escaped_mime}, {var}, sizeof({var}) }},")

    source_lines.append("const ArkAsset ark_assets[] = {")
    source_lines.extend(table_lines)
    source_lines.append("};")
    source_lines.append("")
    source_lines.append(
        f"const size_t ark_asset_count = {len(files)};"
    )
    source_lines.append("")

    return "\n".join(source_lines), header
