"""
`arklight android scaffold` -- Stage 1 of
docs/Backends/ANDROID-BACKEND-IMPLEMENTATION.md.

    arklight android scaffold <build-dir> -o <project-dir>

Templating only, no toolchain required -- see that file's staged-order
table and docs/Foundational/DESIGN-NOTES.md's "v0.0438: Android
backend" section. This module is the CLI-facing counterpart to
`arklight.backend.android.runtime` (the pure template-content builder,
see its own docstring): it owns everything that module deliberately
leaves out -- reading `arklight.config.py`'s `"android"` section
(mirroring `arklight.cli.live_streaming`'s own `"live_streaming"`
read), resolving/validating that config against defaults, copying the
`build-dir` itself into `app/src/main/assets/`, copying in an optional
raw icon/splash image, and writing every generated file to disk. Same
"template builders never touch disk, the CLI module owns filesystem
writes" split `arklight.cli.scaffold` already established for
`arklight new`.

`arklight android scaffold`'s output also includes a ready-to-use
GitHub Actions workflow (`.github/workflows/android-build.yml`,
generated by `runtime.project_files` -- see
`runtime._github_ci_workflow_yml`) with two jobs: builds a debug APK
on GitHub-hosted runners on every push/PR (Stage 2) and installs and
launches it on a throwaway emulator on that same runner to confirm it
doesn't crash immediately on startup (Stage 3). Both are CI-only
build/install verification, no local toolchain required, folded into
this same command rather than a separate subcommand since they cost
nothing to generate. The release-build job (Stage 4) is opt-in --
`arklight android scaffold --release` -- since it's a no-op without a
keystore this tool has no business generating or holding; the flag
just wires the generated workflow to read one from repo secrets at
build time instead, see `runtime._github_ci_workflow_yml`. `arklight
android build` (Stage 5 -- shells out to a *local* `./gradlew
assembleDebug`, requires a JDK on this machine), `arklight android
build --install` (Stage 6 -- `adb install` onto a device/emulator the
user has actually connected), and `arklight android build --release`
(Stage 7 -- the same local shell-out targeting `assembleRelease`) are
separate, not-yet-implemented commands; this module only produces the
project shell, it never invokes Gradle or `adb` itself.

`.github/workflows/` is only discovered by GitHub Actions at a git
repository's *root*. This command has no reliable way to know whether
`output_dir` is meant to become its own repo (in which case writing
`.github/workflows/` there is correct) or is meant to be dropped in as
a subdirectory of an existing repo (in which case it isn't, and the
workflow silently never runs). Rather than guess -- or write files
outside the `output_dir` the caller explicitly asked for -- `scaffold_
project` walks upward from `output_dir` looking for an *already
existing* enclosing `.git` (one that isn't `output_dir` itself),
before generating any files. When found, `output_dir`'s path relative
to that enclosing root is threaded through to `runtime.project_files`
as `project_subdir`, so the generated workflow's Gradle steps already
carry the right `working-directory:` and artifact `path:` for that
layout -- it doesn't just build once moved, no manual editing needed.
The enclosing root itself is also surfaced on
`ScaffoldResult.enclosing_git_root` so the CLI layer
(`arklight.cli.main._cmd_android_scaffold`) can still tell the user
the workflow file needs to physically *move* there (the one thing
this function can't safely do for them, since `output_dir` is the
only place it's been told it may write).
"""

from __future__ import annotations

import json
import re
import shutil
import unicodedata
from dataclasses import dataclass, field
from html.parser import HTMLParser
from pathlib import Path

from arklight.backend.android import runtime
from arklight.config import ConfigError, load_config, section

# Defaults for every key `arklight.config.py`'s `"android"` section
# may set -- see docs/Foundational/DESIGN-NOTES.md's "App identity
# metadata" subsection for the full key list. A project with no
# `arklight.config.py` at all (or one with no `"android"` section)
# still scaffolds a buildable, if generically named and unbranded, app.
#
# `app_name` and `package_id` default to `None` ("the project didn't
# say") rather than a placeholder string, so `scaffold_project` can tell
# "not configured" from "configured" and derive them from the build
# directory instead -- see docs/Proposals/ANDROID-IDENTITY-SYSTEM-BAR-
# SYNC.md sections 2.1/2.2. `_FALLBACK_APP_NAME`/`_FALLBACK_PACKAGE_ID`
# are what an unconfigured, unnamed project ends up with, as before.
_DEFAULTS: dict[str, object] = {
    "app_name": None,
    "package_id": None,
    "status_bar_color": "auto",
    "version_name": "1.0.0",
    "version_code": 1,
    "icon": None,
    "splash": None,
    "orientation": "portrait",
    "edge_to_edge": False,
    "allow_navigation": [],
}

_FALLBACK_APP_NAME = "ARKlight App"
_FALLBACK_PACKAGE_ID = "com.arklight.app"
_DEFAULT_SOURCE = "default -- nothing in the build named the app"

# The compiler's own placeholder `Site(name=...)`. It reaches `<title>`
# on a page that sets none, but it isn't a name anyone chose.
_PLACEHOLDER_SITE_NAME = "arklight-site"

# Namespace of a derived package id. Reverse-domain ids imply you own
# the domain -- fine for a personal test install, not for publishing;
# the CLI says so. See the proposal's section 5.1.
_DERIVED_PACKAGE_PREFIX = "com.arklight."
_MAX_SLUG_LENGTH = 40

# Java + Kotlin hard keywords: an unescaped one as a package segment is
# a compile error in the generated `package` line.
_RESERVED_WORDS = frozenset(
    """abstract as assert boolean break byte case catch char class const
    continue default do double else enum extends false final finally float
    for fun goto if implements import in instanceof int interface is long
    native new null object package private protected public return short
    static strictfp super switch synchronized this throw throws transient
    true try typealias typeof val var void volatile when while""".split()
)

# Config-file `orientation` values -> `android:screenOrientation`
# manifest attribute values (see `runtime.py`'s `project_files`
# docstring: "already resolved to its Android manifest value, e.g.
# 'fullSensor', not the config file's 'sensor'"). "sensor" maps to
# "fullSensor" (all 4 rotations, including upside-down) since that's
# what "let it rotate freely" means in practice for a full-window
# WebView app, not the narrower `sensor` attribute value (which
# excludes the upside-down orientation).
_ORIENTATIONS: dict[str, str] = {
    "portrait": "portrait",
    "landscape": "landscape",
    "sensor": "fullSensor",
    "unspecified": "unspecified",
}

# Package/application IDs are dotted Java-style identifiers: >= 2
# segments, each starting with a letter or underscore, alphanumerics/
# underscores only after that -- what Gradle's own `applicationId`
# validation requires.
_PACKAGE_ID_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)+$")

# Extensions this stage accepts for a raw icon/splash image -- kept
# narrow and explicit rather than accepting anything Android's
# res/drawable/ folder can technically hold, since a mismatched/exotic
# extension here would silently produce a resource file name Gradle's
# resource compiler rejects. See runtime.py's "v1" note on this being
# deliberately unrefined (no cropping/rasterization) for now.
_IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp"}


class AndroidError(Exception):
    """Raised when a build directory can't be scaffolded into an Android project."""


@dataclass
class ScaffoldResult:
    project_dir: Path
    written_paths: list[Path] = field(default_factory=list)
    app_name: str = ""
    package_id: str = ""
    # Set when `project_dir` sits inside an *already existing* git repo
    # (i.e. some ancestor directory has a `.git`) rather than being a
    # repo root itself -- see `_find_enclosing_git_root`. GitHub Actions
    # only discovers `.github/workflows/` at a repo's root, so when this
    # is set the generated workflow needs to move there by hand.
    enclosing_git_root: Path | None = None
    # Whether a `--debug-keystore` was pinned into the project (copied
    # to `app/debug.keystore`) -- see `scaffold_project`'s docstring.
    # When False, the CLI warns: every machine (a fresh CI runner
    # included) will auto-generate its own debug key, so debug APKs
    # from different builds won't share a signature.
    has_debug_keystore: bool = False
    # Where each piece of identity came from, for the CLI to report --
    # see `_resolve_app_name`, `_resolve_package_id` and
    # `_resolve_system_bars`.
    app_name_source: str = ""
    package_id_source: str = ""
    # Opaque `#RRGGBB` driving the bars/window/splash, or None when the
    # Material theme colours are in use.
    system_bar_color: str | None = None
    system_bar_source: str = ""
    # Set when `status_bar_color = "auto"` found a value it couldn't use
    # and fell back to Material; says which value and why.
    system_bar_note: str | None = None
    # True when the package id was set in `arklight.config.py` (so the
    # CLI's "choose your own id" reminder is unnecessary).
    package_id_configured: bool = False


def _find_enclosing_git_root(project_dir: Path) -> Path | None:
    """
    Look for a `.git` in some *already existing* ancestor of
    `project_dir` -- not in `project_dir` itself, which won't exist yet
    at the point `scaffold_project` calls this, and which this function
    has no business creating a repo inside of anyway. Only intended to
    catch the "scaffolding into a subdirectory of a repo you already
    have checked out" case (e.g. `-o android/` inside a site's own
    working copy); doesn't distinguish that from `project_dir` simply
    being deeply nested under an unrelated repo (an unlikely enough
    layout that a false positive there just means an accurate, if
    slightly unnecessary, warning).
    """
    start = project_dir.resolve()
    # `start` may not exist yet (scaffold_project calls this before
    # creating anything); walk from the nearest existing ancestor.
    probe = start
    while not probe.exists():
        parent = probe.parent
        if parent == probe:
            return None
        probe = parent
    for ancestor in [probe, *probe.parents]:
        if (ancestor / ".git").exists():
            # `project_dir` itself already being a repo root is the
            # correct case (`.github/workflows/` belongs right there) --
            # only flag a strict *ancestor* of it.
            return ancestor if ancestor != start else None
    return None


def _validate_package_id(package_id: str) -> None:
    if not isinstance(package_id, str) or not _PACKAGE_ID_RE.match(package_id):
        raise AndroidError(
            f"Invalid android.package_id {package_id!r} -- must be a dotted "
            f"Java-style identifier with at least two segments (letters, "
            f"digits, underscores only; no segment may start with a digit), "
            f"e.g. 'com.example.myapp'."
        )


# --------------------------------------------------------------------
# Identity + system bars derived from the build directory
# (docs/Proposals/ANDROID-IDENTITY-SYSTEM-BAR-SYNC.md section 2)
# --------------------------------------------------------------------


class _HeadScanner(HTMLParser):
    """
    Collect what `index.html`'s `<head>` says about the site: its
    `<title>`, its `theme-color` meta tags and its stylesheet links.
    Stops at `</head>`. Entities are decoded exactly once
    (`convert_charrefs=True`).
    """

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.in_head = False
        self.done = False
        self._in_title = False
        self._title_parts: list[str] = []
        self.theme_colors: list[tuple[str, str]] = []  # (content, media)
        self.stylesheets: list[str] = []

    @property
    def title(self) -> str | None:
        text = " ".join("".join(self._title_parts).split())
        return text or None

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if self.done:
            return
        attr = {k.lower(): (v or "") for k, v in attrs}
        if tag == "head":
            self.in_head = True
        elif tag == "body":
            self.done = True
        elif not self.in_head:
            return
        elif tag == "title":
            self._in_title = True
        elif tag == "meta" and attr.get("name", "").strip().lower() == "theme-color":
            self.theme_colors.append((attr.get("content", ""), attr.get("media", "")))
        elif (
            tag == "link"
            and "stylesheet" in attr.get("rel", "").lower().split()
            and attr.get("href")
        ):
            self.stylesheets.append(attr["href"])

    def handle_endtag(self, tag: str) -> None:
        if self.done:
            return
        if tag == "title":
            self._in_title = False
        elif tag == "head":
            self.in_head = False
            self.done = True

    def handle_data(self, data: str) -> None:
        if self._in_title and not self.done:
            self._title_parts.append(data)


def _scan_head(build_dir: Path) -> _HeadScanner:
    scanner = _HeadScanner()
    try:
        text = (build_dir / "index.html").read_text(encoding="utf-8", errors="replace")
    except OSError:
        return scanner
    scanner.feed(text)
    scanner.close()
    return scanner


def _is_named(name: object) -> bool:
    return (
        isinstance(name, str)
        and bool(name.strip())
        and name.strip().casefold() != _PLACEHOLDER_SITE_NAME
    )


def _resolve_app_name(
    build_dir: Path, configured: object, head: _HeadScanner
) -> tuple[str, str]:
    """
    Pick the app's display name and say where it came from. First hit
    wins: `android.app_name`; the PWA `manifest.json`'s `name` (present
    once `arklight pwa` has run); the home page's `<title>` (which for a
    page with no title of its own is `Site(name=...)`); then the generic
    "ARKlight App". The compiler's placeholder site name doesn't count
    as a name.
    """
    if configured is not None:
        if not isinstance(configured, str) or not configured.strip():
            raise AndroidError(
                f"android.app_name must be a non-empty string, got {configured!r}."
            )
        return configured, "from android.app_name in arklight.config.py"

    manifest = build_dir / "manifest.json"
    if manifest.is_file():
        try:
            data = json.loads(manifest.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            data = None
        name = data.get("name") if isinstance(data, dict) else None
        if _is_named(name):
            return " ".join(name.split()), "from manifest.json name"

    if _is_named(head.title):
        return head.title, "from index.html <title>"  # type: ignore[return-value]

    return _FALLBACK_APP_NAME, _DEFAULT_SOURCE


def _slugify_app_name(app_name: str) -> str:
    """
    Turn an app name into one legal `applicationId` segment: accents
    folded to ASCII, everything non-alphanumeric collapsed to `_`,
    lowercase, a leading digit prefixed with `app_`, a Java/Kotlin
    keyword suffixed with `_app`, nothing ASCII at all becoming `app`,
    at most 40 characters. (A hyphen, the natural separator, isn't legal
    in an `applicationId` segment, hence `_`.)
    """
    folded = unicodedata.normalize("NFKD", app_name).encode("ascii", "ignore").decode("ascii")
    slug = re.sub(r"[^a-z0-9]+", "_", folded.lower()).strip("_")
    slug = slug[:_MAX_SLUG_LENGTH].rstrip("_")
    if not slug:
        return "app"
    if slug[0].isdigit():
        slug = f"app_{slug}"
    if slug in _RESERVED_WORDS:
        slug = f"{slug}_app"
    return slug[:_MAX_SLUG_LENGTH].rstrip("_")


def _resolve_package_id(
    configured: object, app_name: str, app_name_source: str
) -> tuple[str, str]:
    """
    `android.package_id` if set (validated as ever); otherwise
    `com.arklight.<slug of the app name>`; and if nothing named the app,
    the old `com.arklight.app` so a nameless project is unchanged.
    """
    if configured is not None:
        _validate_package_id(configured)  # type: ignore[arg-type]
        return configured, "from android.package_id in arklight.config.py"  # type: ignore[return-value]
    if app_name_source == _DEFAULT_SOURCE:
        return _FALLBACK_PACKAGE_ID, _DEFAULT_SOURCE
    package_id = _DERIVED_PACKAGE_PREFIX + _slugify_app_name(app_name)
    _validate_package_id(package_id)
    return package_id, "derived from app name"


# The 16 basic CSS colour names plus `orange` (and the `grey` spelling
# of `gray`). Anything else named is deliberately not understood: a bar
# painted a colour the page doesn't have is worse than an unmatched one.
_NAMED_COLORS: dict[str, str] = {
    "black": "#000000",
    "silver": "#C0C0C0",
    "gray": "#808080",
    "grey": "#808080",
    "white": "#FFFFFF",
    "maroon": "#800000",
    "red": "#FF0000",
    "purple": "#800080",
    "fuchsia": "#FF00FF",
    "green": "#008000",
    "lime": "#00FF00",
    "olive": "#808000",
    "yellow": "#FFFF00",
    "navy": "#000080",
    "blue": "#0000FF",
    "teal": "#008080",
    "aqua": "#00FFFF",
    "orange": "#FFA500",
}

_HEX_RE = re.compile(r"^#([0-9a-f]{3,4}|[0-9a-f]{6}|[0-9a-f]{8})$")
_FUNC_RE = re.compile(r"^(rgba?|hsla?)\(\s*(.*?)\s*\)$", re.DOTALL)
_NUMBER_RE = re.compile(r"^[+-]?(\d+\.?\d*|\.\d+)(e[+-]?\d+)?$")


def _to_number(token: str, suffix: str = "") -> float | None:
    """Parse `token` as a number, requiring `suffix` (e.g. '%') if given."""
    if suffix:
        if not token.endswith(suffix):
            return None
        token = token[: -len(suffix)]
    return float(token) if _NUMBER_RE.match(token) else None


def _is_opaque_alpha(token: str) -> bool:
    if token.endswith("%"):
        value = _to_number(token, "%")
        return value is not None and value >= 100
    value = _to_number(token)
    return value is not None and value >= 1


def _clamp_byte(value: float) -> int:
    return max(0, min(255, int(value + 0.5)))


def _hsl_to_rgb(h: float, s: float, l: float) -> tuple[int, int, int]:
    h = (h % 360) / 360
    s = max(0.0, min(1.0, s))
    l = max(0.0, min(1.0, l))
    if s == 0:
        v = _clamp_byte(l * 255)
        return v, v, v
    q = l * (1 + s) if l < 0.5 else l + s - l * s
    p = 2 * l - q

    def channel(t: float) -> float:
        t %= 1
        if t < 1 / 6:
            return p + (q - p) * 6 * t
        if t < 1 / 2:
            return q
        if t < 2 / 3:
            return p + (q - p) * (2 / 3 - t) * 6
        return p

    return (
        _clamp_byte(channel(h + 1 / 3) * 255),
        _clamp_byte(channel(h) * 255),
        _clamp_byte(channel(h - 1 / 3) * 255),
    )


def _parse_css_color(value: object) -> str | None:
    """
    Parse an opaque solid CSS colour to `#RRGGBB`, or return None.

    Understood: hex (`#rgb`, `#rrggbb`, and the alpha forms when alpha is
    full), `rgb()`/`rgba()` and `hsl()`/`hsla()` in comma or space
    syntax with full alpha, and the named colours in `_NAMED_COLORS`.
    Not understood (None): gradients, images, `var(...)`, `transparent`,
    any translucent value and any other named colour.
    """
    if not isinstance(value, str):
        return None
    text = value.strip().lower()
    text = re.sub(r"\s*!important\s*$", "", text)
    if not text:
        return None

    if text in _NAMED_COLORS:
        return _NAMED_COLORS[text]

    match = _HEX_RE.match(text)
    if match:
        digits = match.group(1)
        if len(digits) in (3, 4):
            digits = "".join(c * 2 for c in digits)
        if len(digits) == 8:
            if digits[6:] != "ff":
                return None
            digits = digits[:6]
        return "#" + digits.upper()

    match = _FUNC_RE.match(text)
    if not match:
        return None
    func, body = match.group(1), match.group(2)
    tokens = body.replace(",", " ").replace("/", " ").split()
    if len(tokens) not in (3, 4):
        return None
    if len(tokens) == 4 and not _is_opaque_alpha(tokens[3]):
        return None

    if func.startswith("rgb"):
        channels: list[int] = []
        for token in tokens[:3]:
            pct = _to_number(token, "%")
            if pct is not None:
                channels.append(_clamp_byte(pct * 255 / 100))
                continue
            num = _to_number(token)
            if num is None:
                return None
            channels.append(_clamp_byte(num))
        r, g, b = channels
    else:
        hue_token = tokens[0]
        turns = _to_number(hue_token, "turn")
        degrees = _to_number(hue_token, "deg")
        hue = turns * 360 if turns is not None else degrees
        if hue is None:
            hue = _to_number(hue_token)
        sat = _to_number(tokens[1], "%")
        light = _to_number(tokens[2], "%")
        if sat is None:
            sat = _to_number(tokens[1])
        if light is None:
            light = _to_number(tokens[2])
        if hue is None or sat is None or light is None:
            return None
        r, g, b = _hsl_to_rgb(hue, sat / 100, light / 100)
    return f"#{r:02X}{g:02X}{b:02X}"


_CSS_COMMENT_RE = re.compile(r"/\*.*?\*/", re.DOTALL)
_ROOT_RULE_RE = re.compile(r":root\s*\{([^}]*)\}")
_ARK_BG_RE = re.compile(r"--ark-bg\s*:\s*([^;}]+)")


def _stylesheet_ark_bg(build_dir: Path, head: _HeadScanner) -> str | None:
    """
    The raw `--ark-bg` value declared in a `:root` rule of a local
    stylesheet linked from `index.html` -- the one every page shares.
    The last declaration wins, as in the cascade.
    """
    root = build_dir.resolve()
    found: str | None = None
    for href in head.stylesheets:
        href = href.split("#", 1)[0].split("?", 1)[0]
        if not href or "//" in href or ":" in href.split("/", 1)[0]:
            continue  # external, or some other scheme
        candidate = (root / href.lstrip("/")).resolve()
        try:
            candidate.relative_to(root)
        except ValueError:
            continue
        if not candidate.is_file():
            continue
        try:
            css = _CSS_COMMENT_RE.sub("", candidate.read_text(encoding="utf-8", errors="replace"))
        except OSError:
            continue
        for rule in _ROOT_RULE_RE.finditer(css):
            for decl in _ARK_BG_RE.finditer(rule.group(1)):
                found = decl.group(1).strip()
    return found


@dataclass(frozen=True)
class _SystemBars:
    color: str | None  # opaque #RRGGBB, or None = Material theme colours
    source: str
    note: str | None = None


def _resolve_system_bars(build_dir: Path, configured: object, head: _HeadScanner) -> _SystemBars:
    """
    Resolve `android.status_bar_color`: `"material"` (the Material theme
    colours, as before), any single CSS colour, or `"auto"` (default) --
    match the site: a `theme-color` meta tag if there is one, else the
    stylesheet's `--ark-bg`. This is the page's *background*, one colour
    for the whole app, not a pixel average of the rendered page.

    An explicit value that isn't an opaque solid colour is an
    `AndroidError`. An `"auto"` source that isn't one falls back to
    Material and says so in `note`.
    """
    if not isinstance(configured, str) or not configured.strip():
        raise AndroidError(
            f"android.status_bar_color must be 'auto', 'material' or a CSS colour, "
            f"got {configured!r}."
        )
    mode = configured.strip().lower()

    if mode == "material":
        return _SystemBars(None, 'android.status_bar_color = "material"')

    if mode != "auto":
        color = _parse_css_color(configured)
        if color is None:
            raise AndroidError(
                f"Invalid android.status_bar_color {configured!r} -- use 'auto', "
                f"'material', or an opaque solid CSS colour: hex (#1a1a2e), rgb(...), "
                f"hsl(...) or one of the basic colour names (white, black, navy, ...). "
                f"Gradients, images, var(...), transparent and translucent values "
                f"aren't supported."
            )
        return _SystemBars(color, "from android.status_bar_color in arklight.config.py")

    # "auto": a theme-color meta tag first (ignoring dark-only `media`
    # variants, which have no counterpart here yet), then the stylesheet.
    raw: str | None = None
    source = ""
    for content, media in head.theme_colors:
        if "dark" not in media.lower():
            raw, source = content.strip(), "theme-color meta tag"
            break
    if raw is None:
        raw = _stylesheet_ark_bg(build_dir, head)
        source = "stylesheet --ark-bg"

    if raw is None:
        return _SystemBars(
            None,
            "Material theme colours",
            "no theme-color meta tag or --ark-bg found in the build",
        )
    color = _parse_css_color(raw)
    if color is None:
        return _SystemBars(
            None,
            "Material theme colours",
            f"the {source} value {raw!r} isn't a solid opaque colour ARKlight can "
            f"read (gradients, images, var(...) and translucent values aren't "
            f"supported) -- set android.status_bar_color to choose one",
        )
    return _SystemBars(color, f"from {source}")


def _validate_version_code(version_code: object) -> int:
    if not isinstance(version_code, int) or isinstance(version_code, bool):
        raise AndroidError(f"android.version_code must be an int, got {version_code!r}.")
    return version_code


def _resolve_orientation(value: object) -> str:
    if value not in _ORIENTATIONS:
        valid = ", ".join(sorted(_ORIENTATIONS))
        raise AndroidError(f"Unknown android.orientation {value!r} -- valid values: {valid}.")
    return _ORIENTATIONS[value]  # type: ignore[index]


def _resolve_allow_navigation(value: object) -> list[str]:
    """
    Validate `android.allow_navigation`: the external `https` hosts a
    link may load *inside* the app's WebView rather than being handed
    to the system browser (an OAuth or payment domain, say). Hard-fails
    on a malformed entry, like `package_id` does, rather than warning
    and skipping it -- a silently dropped host would send the user to
    the browser mid-flow with nothing at build time saying why.

    Each entry is a bare hostname, optionally `*.`-prefixed to mean
    "any subdomain of" (the bare domain itself is not included). A
    scheme, port or path is rejected, with a message that says so,
    since `"https://login.example.com"` is the natural first guess.
    Entries are lowercased and de-duplicated, order preserved.
    """
    if isinstance(value, str) or not isinstance(value, (list, tuple)):
        raise AndroidError(
            f"android.allow_navigation must be a list of hostnames, got {value!r}."
        )
    hosts: list[str] = []
    for entry in value:
        if not isinstance(entry, str) or not runtime.HOST_PATTERN_RE.match(entry):
            raise AndroidError(
                f"Invalid android.allow_navigation entry {entry!r} -- each entry must be "
                f"a bare hostname such as 'login.example.com', or '*.example.com' to "
                f"allow every subdomain. No scheme (https://), port or path; "
                f"single-label names like 'localhost' and bare wildcards like '*.com' "
                f"are not accepted."
            )
        host = entry.lower()
        if host not in hosts:
            hosts.append(host)
    return hosts


def _resolve_asset(build_dir: Path, rel_path: object, key: str) -> Path:
    """
    Resolve `android.icon`/`android.splash`'s value to a real file
    under `build_dir` -- relative to the build directory root, same
    convention `arklight pwa --icon SRC:...` already uses, since by
    the time `arklight android scaffold` runs, `arklight build` has
    already copied a project's `assets/` into the build output.
    """
    if not isinstance(rel_path, str) or not rel_path:
        raise AndroidError(f"android.{key} must be a non-empty string path, got {rel_path!r}.")

    candidate = (build_dir / rel_path).resolve()
    try:
        candidate.relative_to(build_dir.resolve())
    except ValueError:
        raise AndroidError(
            f"android.{key} {rel_path!r} must stay inside the build directory."
        ) from None

    if not candidate.is_file():
        raise AndroidError(
            f"android.{key} {rel_path!r} not found in {build_dir} -- this path "
            f"is relative to the build directory root, same as `arklight pwa`'s "
            f"--icon."
        )
    if candidate.suffix.lower() not in _IMAGE_EXTENSIONS:
        allowed = ", ".join(sorted(_IMAGE_EXTENSIONS))
        raise AndroidError(
            f"android.{key} {rel_path!r} has an unsupported extension "
            f"{candidate.suffix!r} -- supported: {allowed}."
        )
    return candidate


def _copy_tree(src: Path, dst: Path) -> list[Path]:
    """Copy every file under `src` into `dst`, preserving relative
    structure. Returns the list of files written."""
    written: list[Path] = []
    for item in sorted(src.rglob("*")):
        target = dst / item.relative_to(src)
        if item.is_dir():
            target.mkdir(parents=True, exist_ok=True)
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(item, target)
            written.append(target)
    return written


def scaffold_project(
    build_dir: str | Path,
    *,
    output_dir: str | Path,
    debug_keystore: str | Path | None = None,
    include_release_job: bool = False,
) -> ScaffoldResult:
    """
    Scaffold an Application-mode Android Studio / Gradle project at
    `output_dir` from an existing `arklight build` output directory
    (`build_dir`). Reads app identity from `arklight.config.py`'s
    `"android"` section, found next to `build_dir` (i.e. `build_dir`'s
    parent directory -- the same directory a project's `site.py`
    conventionally lives in, one level up from a build output like
    `ARK/`).

    `debug_keystore`, if given, is copied into the project as
    `app/debug.keystore` and wired up as the `debug` build type's
    signing key -- see the module docstring's "Debug signing" section
    for why you'd want this: without it, every machine (including each
    fresh CI runner) auto-generates its *own* debug key, so a debug APK
    built on one won't share a signature with one built on another and
    `adb install -r`/reinstalling over an existing test install fails.

    `include_release_job`, if True, adds a signed release-build job
    (`assemble-release`) to the generated GitHub Actions workflow --
    off by default, opted into explicitly via `arklight android
    scaffold --release`, since it's a no-op (a job that fails until
    the `RELEASE_KEYSTORE_BASE64`/`RELEASE_KEYSTORE_PASSWORD`/
    `RELEASE_KEY_ALIAS`/`RELEASE_KEY_PASSWORD` repo secrets it expects
    are configured) for anyone who hasn't set that up yet. See
    `runtime._github_ci_workflow_yml`'s docstring for what the job
    does.

    Anything the config doesn't say is derived from the build directory
    -- app name, package id, system-bar colour; see `_resolve_app_name`,
    `_resolve_package_id` and `_resolve_system_bars`, and
    docs/Proposals/ANDROID-IDENTITY-SYSTEM-BAR-SYNC.md.

    Raises AndroidError for a missing/malformed build directory, a
    non-empty `output_dir`, an invalid/malformed `"android"` config
    section, a missing/unsupported icon or splash image, or a missing
    `debug_keystore` file.
    """
    build_dir = Path(build_dir)
    if not build_dir.is_dir():
        raise AndroidError(f"Build directory not found: {build_dir}")
    if not (build_dir / "index.html").is_file():
        raise AndroidError(
            f"{build_dir} has no index.html at its root -- run `arklight build` "
            f"first, then scaffold its output directory. Application mode loads "
            f"exactly one fixed entry page, index.html."
        )

    project_dir = Path(output_dir)
    if project_dir.exists():
        if not project_dir.is_dir():
            raise AndroidError(f"{project_dir} already exists and is not a directory.")
        if any(project_dir.iterdir()):
            raise AndroidError(
                f"{project_dir} already exists and is not empty. Choose a "
                f"different -o directory, or clear it first."
            )

    try:
        config = load_config(build_dir.parent)
    except ConfigError as exc:
        raise AndroidError(str(exc)) from exc
    android_cfg = section(config, "android", _DEFAULTS)

    head = _scan_head(build_dir)
    app_name, app_name_source = _resolve_app_name(build_dir, android_cfg["app_name"], head)
    package_id, package_id_source = _resolve_package_id(
        android_cfg["package_id"], app_name, app_name_source
    )
    system_bars = _resolve_system_bars(build_dir, android_cfg["status_bar_color"], head)

    version_name = android_cfg["version_name"]
    if not isinstance(version_name, str) or not version_name.strip():
        raise AndroidError(
            f"android.version_name must be a non-empty string, got {version_name!r}."
        )

    version_code = _validate_version_code(android_cfg["version_code"])
    orientation = _resolve_orientation(android_cfg["orientation"])
    edge_to_edge = bool(android_cfg["edge_to_edge"])
    allow_navigation = _resolve_allow_navigation(android_cfg["allow_navigation"])

    icon_path = (
        _resolve_asset(build_dir, android_cfg["icon"], "icon")
        if android_cfg["icon"] is not None
        else None
    )
    splash_path = (
        _resolve_asset(build_dir, android_cfg["splash"], "splash")
        if android_cfg["splash"] is not None
        else None
    )

    debug_keystore_path: Path | None = None
    if debug_keystore is not None:
        debug_keystore_path = Path(debug_keystore)
        if not debug_keystore_path.is_file():
            raise AndroidError(f"--debug-keystore file not found: {debug_keystore_path}")

    # Resolved *before* generating files (not just at the end for
    # `ScaffoldResult`, as before) so the workflow template itself can
    # be told whether it's landing at a repo root or a subdirectory of
    # one -- see `runtime._github_ci_workflow_yml`'s `project_subdir`.
    # Safe to call this early: it only walks *already existing*
    # ancestors of `project_dir`, never `project_dir` itself, which is
    # written below and may not exist yet.
    enclosing_git_root = _find_enclosing_git_root(project_dir)
    project_subdir = (
        project_dir.resolve().relative_to(enclosing_git_root).as_posix()
        if enclosing_git_root is not None
        else None
    )

    files = runtime.project_files(
        app_name=app_name,
        package_id=package_id,
        version_name=version_name,
        version_code=version_code,
        orientation=orientation,
        edge_to_edge=edge_to_edge,
        has_custom_icon=icon_path is not None,
        has_splash=splash_path is not None,
        has_debug_keystore=debug_keystore_path is not None,
        include_release_job=include_release_job,
        project_subdir=project_subdir,
        allow_navigation=allow_navigation,
        system_bar_color=system_bars.color,
    )

    written: list[Path] = []
    for rel_path, contents in files.items():
        dest = project_dir / rel_path
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(contents, encoding="utf-8")
        written.append(dest)

    drawable_dir = project_dir / "app/src/main/res/drawable"
    if icon_path is not None:
        dest = drawable_dir / f"ic_launcher_custom{icon_path.suffix.lower()}"
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(icon_path, dest)
        written.append(dest)
    if splash_path is not None:
        dest = drawable_dir / f"splash_image{splash_path.suffix.lower()}"
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(splash_path, dest)
        written.append(dest)
    if debug_keystore_path is not None:
        dest = project_dir / "app/debug.keystore"
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(debug_keystore_path, dest)
        written.append(dest)

    assets_dest = project_dir / "app/src/main/assets"
    written.extend(_copy_tree(build_dir, assets_dest))

    return ScaffoldResult(
        project_dir=project_dir,
        written_paths=sorted(written),
        app_name=app_name,
        package_id=package_id,
        has_debug_keystore=debug_keystore_path is not None,
        enclosing_git_root=enclosing_git_root,
        app_name_source=app_name_source,
        package_id_source=package_id_source,
        system_bar_color=system_bars.color,
        system_bar_source=system_bars.source,
        system_bar_note=system_bars.note,
        package_id_configured=android_cfg["package_id"] is not None,
    )
