"""
`arklight desktop scaffold` -- Linux-only target for now. See
docs/Backends/DESKTOP-BACKEND-IMPLEMENTATION.md for the staged plan
this is Stage 1 of, and docs/Backends/ARKLIGHT_DESKTOP_BACKEND_PROPOSAL.md
for the native-host architecture it implements.

    arklight desktop scaffold <build-dir> -o <project-dir>

Templating + asset-embedding only, no C toolchain required to run this
command itself -- same split `arklight.cli.android` already
established for `arklight android scaffold`: `arklight.backend.
desktop.runtime` is the pure template/content builder (never touches
disk), this module owns everything that leaves out -- reading
`arklight.config.py`'s `"desktop"` section, resolving/validating it
against defaults, reading the build directory's own bytes to embed,
and writing every generated file to disk.

`arklight desktop scaffold`'s output also includes a ready-to-use
GitHub Actions workflow (`.github/workflows/desktop-build.yml`,
generated by `runtime.project_files` -- see `runtime.
_github_ci_workflow_yml`) that builds the project on a GitHub-hosted
Linux runner on every push/PR and uploads the resulting binary as a
downloadable artifact, mirroring `arklight android scaffold`'s own
generated workflow (see `arklight.cli.android`'s module docstring).
Same "`.github/workflows/` is only discovered at a git repo's root"
caveat applies here too: `scaffold_project` walks upward from
`output_dir` looking for an already-existing enclosing `.git` before
generating any files (`_find_enclosing_git_root`, byte-for-byte the
same logic as `arklight.cli.android._find_enclosing_git_root`), and
when found threads `output_dir`'s path relative to that root through
to `runtime.project_files` as `project_subdir` so the workflow's
`make` step already carries the right `working-directory:` -- the
caller (`arklight.cli.main._cmd_desktop_scaffold`) still has to tell
the user to physically move the file there, the one thing this
function can't safely do on its own.

`arklight desktop build <project-dir>` -- Stage 2. Shells out to the
scaffolded project's own `make` (locally, on *this* machine) so the
user doesn't have to `cd` into it themselves; mirrors `arklight
android build`'s not-yet-implemented relationship to `arklight
android scaffold` (same "scaffold owns templating, build owns
shelling out to the real toolchain" split, just not blocked on a
JDK/Android SDK the way that one is -- only a C compiler + `pkg-config`
+ GTK3/WebKit2GTK dev headers, see the generated project's own
README.md). A missing toolchain (no `make`, no `gcc`, no dev headers)
is caught and reported as an actionable message rather than a raw
`FileNotFoundError`/`CalledProcessError` traceback -- this command
has no business installing any of that for the user, only explaining
what's missing. `--run` additionally launches the freshly built
binary (`bin/<binary>`) once `make` succeeds, the same "build, then
immediately try it" convenience `make run` already offers from
inside the project directory -- this just saves the `cd`.
"""

from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

from arklight.backend.desktop import runtime
from arklight.config import ConfigError, load_config, section

# Defaults for every key `arklight.config.py`'s `"desktop"` section may
# set. A project with no `arklight.config.py` at all (or one with no
# `"desktop"` section) still scaffolds a buildable, if generically
# named, app -- same "still works with zero config" contract the
# Android backend's `_DEFAULTS` follows.
_DEFAULTS: dict[str, object] = {
    "app_name": "ARKlight App",
    "app_id": "com.arklight.app",
    "window_title": None,  # None -> falls back to app_name, see below
    "width": 1024,
    "height": 768,
    "resizable": True,
}

# Targets this command currently accepts. A single-entry tuple, not
# just a hardcoded string check, so the one place that needs to grow
# when a second platform lands is this line plus whatever that
# platform's own runtime module turns out to need -- not a rewrite of
# the validation shape.
SUPPORTED_TARGETS = ("linux",)

# Same shape as `arklight.cli.android._PACKAGE_ID_RE` -- a reverse-DNS
# identifier, >= 2 dotted segments, each starting with a letter or
# underscore. Used here as the `.desktop` launcher's filename and the
# window's program name, not a Python/Java package, but the same
# "dotted, namespaced identifier" convention avoids inventing a
# second syntax for what is conceptually the same kind of value.
_APP_ID_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*(\.[A-Za-z_][A-Za-z0-9_]*)+$")


class DesktopError(Exception):
    """Raised when a build directory can't be scaffolded into a desktop project."""


def _find_enclosing_git_root(project_dir: Path) -> Path | None:
    """
    Look for a `.git` in some *already existing* ancestor of
    `project_dir` -- not in `project_dir` itself, which won't exist yet
    at the point `scaffold_project` calls this, and which this function
    has no business creating a repo inside of anyway. Only intended to
    catch the "scaffolding into a subdirectory of a repo you already
    have checked out" case (e.g. `-o desktop/` inside a site's own
    working copy); doesn't distinguish that from `project_dir` simply
    being deeply nested under an unrelated repo (an unlikely enough
    layout that a false positive there just means an accurate, if
    slightly unnecessary, warning).

    Byte-for-byte the same logic as
    `arklight.cli.android._find_enclosing_git_root` -- kept as its own
    copy rather than a shared import since each backend's `cli` module
    is otherwise self-contained (mirrors `arklight.cli.scaffold`/
    `arklight.cli.android`'s existing "no cross-imports between sibling
    CLI modules" shape), and the two are small and unlikely to drift.
    """
    start = project_dir.resolve()
    # `start` may not exist yet (scaffold_project calls this before
    # creating anything); walk from the nearest existing ancestor.
    probe = start
    while not probe.exists():
        parent = probe.parent
        if parent == probe:
            return None
        probe = parent
    for ancestor in [probe, *probe.parents]:
        if (ancestor / ".git").exists():
            # `project_dir` itself already being a repo root is the
            # correct case (`.github/workflows/` belongs right there) --
            # only flag a strict *ancestor* of it.
            return ancestor if ancestor != start else None
    return None


@dataclass
class ScaffoldResult:
    project_dir: Path
    written_paths: list[Path] = field(default_factory=list)
    app_name: str = ""
    app_id: str = ""
    binary_name: str = ""
    target: str = "linux"
    # Set when `project_dir` sits inside an *already existing* git repo
    # (i.e. some ancestor directory has a `.git`) rather than being a
    # repo root itself -- see `_find_enclosing_git_root`. GitHub Actions
    # only discovers `.github/workflows/` at a repo's root, so when this
    # is set the generated workflow needs to move there by hand. Same
    # field, same reasoning, as `arklight.cli.android.ScaffoldResult`'s
    # own `enclosing_git_root`.
    enclosing_git_root: Path | None = None


def _validate_app_id(app_id: object) -> str:
    if not isinstance(app_id, str) or not _APP_ID_RE.match(app_id):
        raise DesktopError(
            f"Invalid desktop.app_id {app_id!r} -- must be a dotted, reverse-DNS-style "
            f"identifier with at least two segments (letters, digits, underscores only; "
            f"no segment may start with a digit), e.g. 'com.example.myapp'."
        )
    return app_id


def _validate_dimension(value: object, key: str) -> int:
    if not isinstance(value, int) or isinstance(value, bool) or value <= 0:
        raise DesktopError(f"desktop.{key} must be a positive int, got {value!r}.")
    return value


def _read_build_dir(build_dir: Path) -> dict[str, bytes]:
    """Read every file under `build_dir` into memory, keyed by its
    build-relative POSIX path (e.g. `"assets/logo.svg"`) -- the same
    key shape `assets.gen.c`'s lookup table uses. Sorted so the
    embedded asset table (and therefore `assets.gen.c` byte-for-byte)
    is deterministic between runs, same reasoning
    `runtime.generate_assets_source`'s docstring calls out."""
    files: dict[str, bytes] = {}
    for item in sorted(build_dir.rglob("*")):
        if item.is_file():
            rel = item.relative_to(build_dir).as_posix()
            files[rel] = item.read_bytes()
    return files


def scaffold_project(
    build_dir: str | Path,
    *,
    output_dir: str | Path,
    target: str = "linux",
) -> ScaffoldResult:
    """
    Scaffold a native desktop host project at `output_dir` from an
    existing `arklight build` output directory (`build_dir`). Reads
    app identity from `arklight.config.py`'s `"desktop"` section,
    found next to `build_dir` (i.e. `build_dir`'s parent directory --
    same convention `arklight.cli.android.scaffold_project` already
    uses for its `"android"` section).

    `target` must be `"linux"` -- the only platform this backend
    supports so far (see `SUPPORTED_TARGETS` and
    DESKTOP-BACKEND-IMPLEMENTATION.md's staged plan for Windows/macOS).
    Exposed as a keyword now, rather than assumed, so the CLI layer
    and this function agree on one validated value instead of the CLI
    silently hardcoding "linux" past this function's own checks.

    Raises DesktopError for an unsupported `target`, a missing/malformed
    build directory, a non-empty `output_dir`, or an invalid/malformed
    `"desktop"` config section.
    """
    if target not in SUPPORTED_TARGETS:
        supported = ", ".join(SUPPORTED_TARGETS)
        raise DesktopError(
            f"Unsupported desktop target {target!r} -- only {supported} is implemented "
            f"so far, see docs/Backends/DESKTOP-BACKEND-IMPLEMENTATION.md."
        )

    build_dir = Path(build_dir)
    if not build_dir.is_dir():
        raise DesktopError(f"Build directory not found: {build_dir}")
    if not (build_dir / "index.html").is_file():
        raise DesktopError(
            f"{build_dir} has no index.html at its root -- run `arklight build` first, "
            f"then scaffold its output directory. The desktop host loads exactly one "
            f"fixed entry page, index.html."
        )

    project_dir = Path(output_dir)
    if project_dir.exists():
        if not project_dir.is_dir():
            raise DesktopError(f"{project_dir} already exists and is not a directory.")
        if any(project_dir.iterdir()):
            raise DesktopError(
                f"{project_dir} already exists and is not empty. Choose a different "
                f"-o directory, or clear it first."
            )

    try:
        config = load_config(build_dir.parent)
    except ConfigError as exc:
        raise DesktopError(str(exc)) from exc
    desktop_cfg = section(config, "desktop", _DEFAULTS)

    app_name = desktop_cfg["app_name"]
    if not isinstance(app_name, str) or not app_name.strip():
        raise DesktopError(f"desktop.app_name must be a non-empty string, got {app_name!r}.")

    app_id = _validate_app_id(desktop_cfg["app_id"])

    window_title = desktop_cfg["window_title"]
    if window_title is None:
        window_title = app_name
    elif not isinstance(window_title, str) or not window_title.strip():
        raise DesktopError(
            f"desktop.window_title must be a non-empty string (or None), got {window_title!r}."
        )

    width = _validate_dimension(desktop_cfg["width"], "width")
    height = _validate_dimension(desktop_cfg["height"], "height")

    resizable = desktop_cfg["resizable"]
    if not isinstance(resizable, bool):
        raise DesktopError(f"desktop.resizable must be a bool, got {resizable!r}.")

    # See `_find_enclosing_git_root`'s own docstring, and
    # `arklight.cli.android.scaffold_project`'s identical check this
    # mirrors: `.github/workflows/` is only discovered by GitHub
    # Actions at a git repository's root, so when `project_dir` is
    # nested inside an already-existing repo, the generated workflow's
    # `make` step needs a `working-directory:` (and its uploaded
    # artifact path a matching prefix) for the layout it'll actually
    # run from once moved there by hand.
    enclosing_git_root = _find_enclosing_git_root(project_dir)
    project_subdir = None
    if enclosing_git_root is not None:
        project_subdir = project_dir.resolve().relative_to(enclosing_git_root).as_posix()

    build_files = _read_build_dir(build_dir)

    files = runtime.project_files(
        app_name=app_name,
        app_id=app_id,
        window_title=window_title,
        width=width,
        height=height,
        resizable=resizable,
        project_subdir=project_subdir,
    )
    assets_c, assets_h = runtime.generate_assets_source(build_files)
    files["assets.gen.c"] = assets_c
    files["assets.gen.h"] = assets_h

    written: list[Path] = []
    for rel_path, contents in files.items():
        dest = project_dir / rel_path
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(contents, encoding="utf-8")
        written.append(dest)

    return ScaffoldResult(
        project_dir=project_dir,
        written_paths=sorted(written),
        app_name=app_name,
        app_id=app_id,
        binary_name=runtime.binary_name(app_name),
        target=target,
        enclosing_git_root=enclosing_git_root,
    )


@dataclass
class BuildResult:
    project_dir: Path
    binary_path: Path
    # Whether `--run` was passed *and* the binary was actually
    # launched -- distinct from `--run` merely being requested, since
    # a failed `make` never reaches the run step at all (see
    # `build_project`'s early raise on a nonzero `make` exit).
    ran: bool = False


def _find_built_binary(project_dir: Path) -> Path:
    """
    Locate the single binary `make` just produced under `project_dir/
    bin/`. Scaffolded Makefiles always build exactly one `BIN :=
    bin/<binary>` target (see `runtime._makefile`), so rather than
    re-deriving `<binary>` from `arklight.config.py` a second time
    here (and risking it disagreeing with what the Makefile actually
    used, e.g. after a hand-edited Makefile), this just looks at what
    `bin/` actually contains.
    """
    bin_dir = project_dir / "bin"
    candidates = sorted(p for p in bin_dir.glob("*") if p.is_file())
    if not candidates:
        raise DesktopError(
            f"`make` reported success but no binary was found in {bin_dir}/ -- "
            f"the project's Makefile may have been hand-edited to build "
            f"somewhere else. Check its `BIN :=` line."
        )
    if len(candidates) > 1:
        names = ", ".join(p.name for p in candidates)
        raise DesktopError(
            f"Found more than one file in {bin_dir}/ ({names}) -- expected "
            f"exactly one build output. Clear {bin_dir}/ (e.g. `make clean`) "
            f"and try again."
        )
    return candidates[0]


def build_project(project_dir: str | Path, *, run: bool = False) -> BuildResult:
    """
    Build an already-scaffolded (`arklight desktop scaffold`) project
    by shelling out to its own `make`, then (if `run` is True) launch
    the resulting `bin/<binary>`.

    Raises DesktopError for a missing `project_dir`/`Makefile` (i.e.
    not actually a scaffolded project), a missing `make`/C toolchain
    on this machine, or a `make` invocation that exits nonzero (its
    own stderr -- streamed straight through, not captured -- carries
    the real reason, e.g. a missing GTK3/WebKit2GTK dev package; this
    just adds the toolchain-not-found case `make` itself can't
    explain, since that failure happens before `make` even starts).
    """
    project_dir = Path(project_dir)
    if not project_dir.is_dir():
        raise DesktopError(f"Project directory not found: {project_dir}")
    if not (project_dir / "Makefile").is_file():
        raise DesktopError(
            f"{project_dir} has no Makefile -- run `arklight desktop scaffold` "
            f"first, then build its output directory."
        )

    try:
        # stdout/stderr deliberately left to inherit the caller's (not
        # captured) -- `make`'s own compiler errors/warnings are the
        # actionable content on a failure, and buffering them behind a
        # captured-then-reprinted round-trip would only delay a build
        # that itself already streams progress as it goes.
        subprocess.run(["make"], cwd=project_dir, check=True)
    except FileNotFoundError as exc:
        raise DesktopError(
            "`make` was not found on this machine. Install a C toolchain "
            "(build-essential/base-devel/\"Development Tools\", pkg-config, "
            "and the GTK3 + WebKit2GTK dev headers) -- see this project's own "
            "README.md for the exact packages per distro -- then try again."
        ) from exc
    except subprocess.CalledProcessError as exc:
        raise DesktopError(
            f"`make` failed (exit code {exc.returncode}) -- see its output "
            f"above for the reason (commonly a missing GTK3/WebKit2GTK dev "
            f"package; see this project's README.md for the exact packages "
            f"per distro)."
        ) from exc

    binary_path = _find_built_binary(project_dir)

    ran = False
    if run:
        # Same "let it inherit stdout/stderr" reasoning as the `make`
        # call above -- a GUI app's own diagnostics (GTK/WebKit
        # warnings, an ark: scheme handler error, ...) are exactly
        # what a user reaching for `--run` wants to see, not a
        # captured buffer they'd have to go dig up separately.
        try:
            subprocess.run([str(binary_path)], cwd=project_dir, check=True)
        except FileNotFoundError as exc:
            raise DesktopError(
                f"Built {binary_path}, but couldn't launch it -- the binary "
                f"itself is missing or not executable."
            ) from exc
        except subprocess.CalledProcessError as exc:
            raise DesktopError(
                f"{binary_path} exited with code {exc.returncode} -- see its "
                f"own output above for why (commonly no display available, "
                f"e.g. running --run over SSH with no X11/Wayland forwarding)."
            ) from exc
        ran = True

    return BuildResult(project_dir=project_dir, binary_path=binary_path, ran=ran)
